// BazaarLink — OpenAI-compatible gateway (bazaarlink.ai). Free tier routes
// via `auto:free` (4M tokens/day, zero cost, no credit card); the rest of the
// catalog is pay-per-use at the model's vendor rate. Port of OmniRoute #10174-era
// gateway batch (hasFree free tier).
export default {
  id: "bazaarlink",
  priority: 60,
  alias: "bzl",
  uiAlias: "bzl",
  display: {
    name: "BazaarLink",
    icon: "storefront",
    color: "#10B981",
    textIcon: "BZ",
    website: "https://bazaarlink.ai",
    notice: {
      apiKeyUrl: "https://bazaarlink.ai",
      text: "OpenAI-compatible gateway with a free tier: `auto:free` routes to zero-cost inference (4M tokens/day, no credit card). Sign up at bazaarlink.ai for an API key; the paid catalog (Claude, GPT-5.5, Grok, Gemini, GLM, Kimi, MiniMax, Qwen, Mistral, Llama, Nemotron) bills at vendor rates.",
    },
  },
  category: "apikey",
  authType: "apikey",
  authHint: "Create an API key at bazaarlink.ai. Use model `auto:free` for the zero-cost free tier.",
  hasFree: true,
  transport: {
    baseUrl: "https://bazaarlink.ai/api/v1/chat/completions",
    format: "openai",
  },
  models: [
    { id: "auto:free", name: "Auto Free (Zero Cost)" },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini" },
    { id: "gpt-5.4-nano", name: "GPT-5.4 Nano" },
    { id: "grok-4.3", name: "Grok 4.3" },
    { id: "grok-4.20", name: "Grok 4.20" },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash" },
    { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite" },
    { id: "gemma-4-31b-it", name: "Gemma 4 31B" },
    { id: "gemma-4-26b-a4b-it", name: "Gemma 4 26B A4B" },
    { id: "deepseek-v3.2", name: "DeepSeek V3.2" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5", name: "GLM 5" },
    { id: "mimo-v2.5-pro", name: "MiMo-V2.5-Pro" },
    { id: "mimo-v2.5", name: "MiMo-V2.5" },
    { id: "minimax-m3", name: "MiniMax M3", contextLength: 1048576, supportsVision: true },
    { id: "minimax-m2.7", name: "MiniMax M2.7" },
    { id: "minimax-m2.5", name: "MiniMax M2.5" },
    { id: "llama-4-maverick", name: "Llama 4 Maverick" },
    { id: "llama-4-scout", name: "Llama 4 Scout" },
    { id: "llama-3.3-70b-instruct", name: "Llama 3.3 70B" },
    { id: "qwen3.6-plus", name: "Qwen 3.6 Plus" },
    { id: "mistral-large-2512", name: "Mistral Large 3" },
    { id: "mistral-medium-3.1", name: "Mistral Medium 3.1" },
    { id: "mistral-small-2603", name: "Mistral Small 4" },
    { id: "nemotron-3-super-120b-a12b", name: "Nemotron 3 Super" },
  ],
};
